### ISSUE TITLE
Card

### ISSUE THREAD

**Issue by ntlfox** [ntlfox/vanilla-js-game#1]
As a user 
i want to have a card form
so that i can create new cards

###Acceptance criteria
- [] Has title, content and tags
- [] title and content are text
- [] tags in an optional list of text
- [] it can only be sent, if content and title is filled out

###Design/Wireframe/Scribble is attached

### Tasks
- [] Create Form component
- [] Add styling
- [] Add component to docz
- [] Add integration test
- [] Update backend
